version: '3'
services:
  sparql-engine-for-python:
    container_name: sparql-engine-for-openpredict
    build: .
    restart: unless-stopped
    environment: 
      VIRTUAL_HOST: sparql-openpredict.137.120.31.102.nip.io
      LETSENCRYPT_HOST: sparql-openpredict.137.120.31.102.nip.io
      VIRTUAL_PORT: 80
    # ports:
    #   - 8000:80

