version: '3'
services:
  rdflib-endpoint:
    container_name: rdflib-endpoint-openpredict
    build: .
    restart: unless-stopped
    environment: 
      VIRTUAL_HOST: sparql-openpredict.137.120.31.102.nip.io
      LETSENCRYPT_HOST: sparql-openpredict.137.120.31.102.nip.io
      VIRTUAL_PORT: 80
    # ports:
    #   - 8000:80

